export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS"
export const SEND_EMAIL_FAILURE = "SEND_EMAIL_FAILURE"
export const SEND_EMAIL_REQUEST = "SEND_EMAIL_REQUEST"

export const TOGGLE_MODAL = "TOGGLE_MODAL"

export const CHANGE_LANG_ENG = "CHANGE_LANG_ENG"
export const CHANGE_LANG_THAI = "CHANGE_LANG_THAI"